#!/usr/bin/env bash
# Configure domain zone:
# www --> 530662-lb-01 54.85.99.244
# web-01 --> 530662-web-01 34.232.69.228
# web-02 --> 530662-web-02 54.88.88.85

subdomains_all=( "www" "lb-01" "web-01" "web-02" )

runDig () {
    subdomain=$1
    domain=$2

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
    domain="$1"
    for i in "${subdomains_all[@]}"
    do
	runDig "$i" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    runDig "$subdomain" "$domain"
fi
